// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiV8IxpbSAXyxmHmDC90Hxe0sbTSxZJf4',
    appId: '1:831119698800:web:ef2fd5a1458f7811c5fdb5',
    messagingSenderId: '831119698800',
    projectId: 'her-elegance-app',
    authDomain: 'her-elegance-app.firebaseapp.com',
    storageBucket: 'her-elegance-app.firebasestorage.app',
    measurementId: 'G-KVH34TP7HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSYT0Pm54kvLVN0IQ3nnFj7FvkzgFcsoE',
    appId: '1:831119698800:android:9edaf588db20bae9c5fdb5',
    messagingSenderId: '831119698800',
    projectId: 'her-elegance-app',
    storageBucket: 'her-elegance-app.firebasestorage.app',
  );
}
